export const DISPLAY_MESSAGE = 'DISPLAY_MESSAGE';

export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
export const GET_ORGANIZATIONS_SUCCESS='GET_ORGANIZATIONS_SUCCESS';
export const ADD_ORGANIZATION ='ADD_ORGANIZATION';

export const GET_IRRIGATIONGROUPS = 'GET_IRRIGATIONGROUPS';
export const GET_IRRIGATIONGROUPS_SUCCESS='GET_IRRIGATIONGROUPS_SUCCESS';
export const ADD_IRRIGATIONGROUP='ADD_IRRIGATIONGROUP';

export const GET_FAILURE = 'GET_FAILURE';
export const ADD_FAILURE = 'ADD_FAILURE';
export const CLEAR_ERROR='CLEAR_ERROR';
export const ADD_SUCCESS='ADD_SUCCESS';




